version: 2.1
jobs:
  "build-images":
    docker:
      - image: alpine:3.16
    steps:
      - checkout
      - setup_remote_docker:
          version: 20.10.12
          docker_layer_caching: true
      - run:
          name: Install deps
          command: |
            apk update
            apk add make bash git docker docker-cli-buildx
      - run:
          name: Prepare env
          command: |
            docker run --rm --privileged multiarch/qemu-user-static --reset -p yes
            docker context create falco-env
            docker buildx create falco-env --driver docker-container --use
      - run:
          name: Login to registry
          command: |
            echo ${DOCKERHUB_SECRET} | docker login -u ${DOCKERHUB_USER} --password-stdin
      - run:
          name: Build and publish kernel_crawler image
          command: |
            docker buildx build --push \
              --platform "arm64,amd64" \
              -t falcosecurity/kernel-crawler:${CIRCLE_TAG} \
              -t falcosecurity/kernel-crawler:latest \
              -f docker/Dockerfile .

workflows:
  version: 2.1
  release:
    jobs:
      - "build-images":
          context:
            - falco
          filters:
            tags:
              only: /.*/
            branches:
              ignore: /.*/
