name: CI Build
on:
  pull_request:
    branches: [main]
  push:
    branches: [main]

jobs:
  test:
    name: test kernel-crawler
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo ⤵️
        uses: actions/checkout@v3
        
      - name: Install deps
        run: |
          sudo apt update
          sudo apt install python3 python3-pip python3-pygit2 jq
  
      - name: Install crawler
        run: |
          pip3 install .
          
      - name: Run crawler
        run: |
          kernel-crawler crawl --distro "*" --out_fmt driverkit > kernels.json
          
      - name: Validate json
        run: |
          cat kernels.json | jq empty
      
      - uses: actions/upload-artifact@v3
        with:
          path: kernels.json
