---
name: Docker
on:
  pull_request:
    branches:
      - main
    paths:
      - 'docker/*'

jobs:
  build:
    name: Build Dockerfile
    runs-on: ubuntu-latest
    outputs:
      dockerfile_changed: ${{ steps.filter.outputs.docker }}
    steps:
      - name: Checkout repo ⤵️
        uses: actions/checkout@eef61447b9ff4aafe5dcd4e0bbf5d482be7e7871 # v4.2.1

      # test that the Dockerfile builds at all
      # CircleCI handles pushes for now
      - name: Build Image
        uses: docker/build-push-action@4f58ea79222b3b9dc2c8bbdd6debcef730109a75 # v6.9.0
        with:
          file: docker/Dockerfile
          context: .
          push: false
          tags: falcosecurity/kernel-crawler:test
