---
name: Lint
on:
  pull_request:
    branches:
      - main

jobs:
  lint:
    name: Lints and Scans
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo ⤵️
        uses: actions/checkout@eef61447b9ff4aafe5dcd4e0bbf5d482be7e7871 # v4.2.1

      - name: Lint Dockerfile
        uses: hadolint/hadolint-action@54c9adbab1582c2ef04b2016b760714a4bfde3cf # v3.1.0
        with:
          dockerfile: docker/Dockerfile
          ignore: DL3008

      - name: Lint kernel-crawler
        uses: cclauss/GitHub-Action-for-pylint@45e14ae074fb20b6b176a5d803ec05eb4e25b3f0 # 06.0
        with:
          args: "pip install -r requirements.txt ; pylint kernel_crawler"
        continue-on-error: true  # allow failure for now

      - name: Lint YAML
        uses: karancode/yamllint-github-action@fdef6bc189425ecc84cc4543b2674566c0827053 # v2.1.1
        with:
          yamllint_file_or_dir: '.github/workflows/'
          yamllint_strict: false
          yamllint_comment: false
          yamllint_config_filepath: .yamllint
