---
name: Lint
on:
  pull_request:
    branches:
      - main

jobs:
  lint:
    name: Lints and Scans
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo ⤵️
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Lint Dockerfile
        uses: hadolint/hadolint-action@54c9adbab1582c2ef04b2016b760714a4bfde3cf # v3.1.0
        with:
          dockerfile: docker/Dockerfile
          ignore: DL3008

      - name: Lint kernel-crawler
        uses: cclauss/GitHub-Action-for-pylint@8ef4d22e119fb1cdc0f58f2e95cb1f8d8b0d55e6 # 0.7.0
        with:
          args: "pip install -r requirements.txt ; pylint kernel_crawler"
        continue-on-error: true  # allow failure for now

      - name: Lint YAML
        uses: karancode/yamllint-github-action@fdef6bc189425ecc84cc4543b2674566c0827053 # v2.1.1
        with:
          yamllint_file_or_dir: '.github/workflows/'
          yamllint_strict: false
          yamllint_comment: false
          yamllint_config_filepath: .yamllint
