---
name: Test
on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  paths-filter:
    runs-on: ubuntu-latest
    outputs:
      crawler_changed: ${{ steps.filter.outputs.crawler }}
    steps:
      - uses: actions/checkout@eef61447b9ff4aafe5dcd4e0bbf5d482be7e7871 # v4.2.1
      - uses: dorny/paths-filter@de90cc6fb38fc0963ad72b210f1f284cd68cea36 # v3.0.2
        id: filter
        with:
          filters: |
            crawler:
              - 'kernel_crawler/**'

  test:
    name: test kernel-crawler
    runs-on: ubuntu-latest
    needs: paths-filter
    if: needs.paths-filter.outputs.crawler_changed == 'true'
    steps:
      - name: Checkout repo ⤵️
        uses: actions/checkout@eef61447b9ff4aafe5dcd4e0bbf5d482be7e7871 # v4.2.1

      - name: Run crawler
        id: crawler
        uses: ./

      - uses: actions/upload-artifact@b4b15b8c7c6ac21ea08fcf65892d2ee8f75cf882 # v4.4.3
        with:
          path: ${{ steps.crawler.outputs.json }}
