---
name: Test
on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  paths-filter:
    runs-on: ubuntu-latest
    outputs:
      crawler_changed: ${{ steps.filter.outputs.crawler }}
    steps:
      - uses: actions/checkout@v4
      - uses: dorny/paths-filter@v2
        id: filter
        with:
          filters: |
            crawler:
              - 'kernel_crawler/**'

  test:
    name: test kernel-crawler
    runs-on: ubuntu-latest
    needs: paths-filter
    if: needs.paths-filter.outputs.crawler_changed == 'true'
    steps:
      - name: Checkout repo ⤵️
        uses: actions/checkout@v4

      - name: Run crawler
        id: crawler
        uses: ./

      - uses: actions/upload-artifact@v3
        with:
          path: ${{ steps.crawler.outputs.json }}
