---
name: Update Kernels

on:
  workflow_dispatch:
  schedule:
    - cron: '30 6 * * *'

# Checks if any concurrent jobs is running for kernels CI and eventually cancel it.
concurrency:
  group: kernels-ci
  cancel-in-progress: true

jobs:
  update-kernels:
    runs-on: ubuntu-latest
    container:
      image: falcosecurity/kernel-crawler:latest
      options: -u root
    permissions:
      contents: read
      pages: write
      id-token: write
    steps:
      - name: Checkout crawler
        uses: actions/checkout@v3

      - name: Run crawler for x86_64
        run: |
          mkdir $RUNNER_TEMP/x86_64
          kernel-crawler crawl --distro="*" > $RUNNER_TEMP/x86_64/list.json

      - name: Run crawler for aarch64
        run: |
          mkdir $RUNNER_TEMP/aarch64
          kernel-crawler crawl --distro="*" --arch=aarch64 > $RUNNER_TEMP/aarch64/list.json

      - name: Install deps
        run: |
          apt update
          apt install -y jq

      - name: Validate jsons
        run: |
          cat $RUNNER_TEMP/x86_64/list.json | jq empty
          cat $RUNNER_TEMP/aarch64/list.json | jq empty

      - name: Move everything under site folder
        run: |
          mkdir site/
          mv index.html site/
          mkdir site/aarch64/
          $RUNNER_TEMP/aarch64/list.json site/aarch64
          mkdir site/x86_64/
          mv $RUNNER_TEMP/x86_64/list.json site/x86_64/

      - uses: actions/upload-pages-artifact@v1
        with:
          path: 'site'

      - id: deployment
        uses: actions/deploy-pages@v1
