---
name: Update Kernels

on:
  workflow_dispatch:
  schedule:
    - cron: '30 6 * * *'

# Checks if any concurrent jobs is running for kernels CI and eventually cancel it.
concurrency:
  group: kernels-ci
  cancel-in-progress: true

jobs:
  update-kernels:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pages: write
      id-token: write
    steps:
      - name: Run crawler for x86_64
        id: crawler_x86_64
        uses: falcosecurity/kernel-crawler@main
        with:
          arch: 'x86_64'

      - name: Run crawler for aarch64
        id: crawler_aarch64
        uses: falcosecurity/kernel-crawler@main
        with:
          arch: 'aarch64'

      - name: Move generated files to site folder
        run: |
          mkdir site/x86_64
          mv ${{ steps.crawler_x86_64.outputs.json }} site/x86_64/list.json
          mkdir site/aarch64
          mv ${{ steps.crawler_aarch64.outputs.json }} site/aarch64/list.json

      - uses: actions/upload-pages-artifact@v1
        with:
          path: 'site'

      - id: deployment
        uses: actions/deploy-pages@v1
